In [11]:
#7.1
import numpy as np
from numpy import linalg as la

a1 = np.array([1,2,3])
a2 = np.array([0,-4,1])
a3 = np.array([0,3,-1])
aaa = np.stack((a1, a2, a3), axis = 0)
print(la.det(aaa))
b = np.array([2,2,-1])
minv = la.inv(aaa)
print(minv@b)
print(np.array_equal(aaa.T, la.inv(aaa)))
labda, v = la.eig(aaa)
print(labda)

1.0
[10. -1. -2.]
False
[ 1.         -4.79128785 -0.20871215]


In [25]:
#7.3
import numpy as np
from numpy import linalg as la
a1 = (180-123)*2*np.pi/360
a2 = (90-27.4)*2*np.pi/360
a3 = (192.25)*2*np.pi/360
def ex(tita):
    return np.stack((np.array([np.cos(tita),np.sin(tita),0]),np.array([-1*np.sin(tita),np.cos(tita),0]) ,np.array([0,0,1])),axis=0)
def ey(tita):
    return np.stack((np.array([np.cos(tita),0,-1*np.sin(tita)]),np.array([0,1,0]) ,np.array([np.sin(tita),0,np.cos(tita)])),axis=0)
def ez(tita):
    return np.stack((np.array([np.cos(tita),np.sin(tita),0]),np.array([-1*np.sin(tita),np.cos(tita),0]) ,np.array([0,0,1])),axis=0)
    
ee = ex(a1)@ey(a2)@ez(a3)
print(ee)

test = np.array([6,7,8])
print(la.norm(test))
print(la.norm(ee@test))

labda, v = la.eig(ee)
print(labda)

p1 = (27.4)*2*np.pi/360
p2 = (192.25)*2*np.pi/360

pole = np.array([np.cos(p1)*np.cos(p2), np.cos(p1)*np.sin(p2), np.sin(p1)])

print(pole)
print(la.norm(pole))

epole = ee@pole
print(epole)
print(la.norm(epole))

[[-0.06698874 -0.87275577 -0.48353891]
 [ 0.49272847 -0.45034696  0.74458463]
 [-0.86760081 -0.1883746   0.46019978]]
12.206555615733702
12.206555615733702
[-0.52856796+0.84889099j -0.52856796-0.84889099j  1.        +0.j        ]
[-0.86760081 -0.1883746   0.46019978]
1.0
[ 5.55111512e-17 -5.55111512e-17  1.00000000e+00]
1.0


In [28]:
#7.5

x = np.array([1.2, 2.0, 3.1, 4.4, 4.9, 5.8, 6.9, 8.0, 9.1, 9.9])
y = np.array([0.3, 0.5, 0.7, 0.8, 1.3, 1.6, 2.0, 2.3, 2.9, 3.0])


poly = []
for i in range(len(x)):